version: '3.1'

services:
  customerinfodb:
    image: postgres
  
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile
 
volumes:
  postgres_data:

networks:
  discount:
    driver: bridge