// <auto-generated />
using System;
using Discount.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Discount.Infrastructure.init
{
    [DbContext(typeof(CustomerInfoContext))]
    partial class CustomerInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Discount.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SegmentType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SegmentType");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Discount.Domain.Entities.Segment", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("numeric");

                    b.HasKey("Type");

                    b.ToTable("Segment");
                });

            modelBuilder.Entity("Discount.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Discount.Domain.Entities.Segment", "Segment")
                        .WithMany("Customers")
                        .HasForeignKey("SegmentType");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Discount.Domain.Entities.Segment", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
